image: mcr.microsoft.com/dotnet/sdk:7.0
stages:
  - build
variables:
  VINTAGE_STORY_MODDING: '/VintageStory'
  SERVER_TYPE: 'stable'
  SERVER_VERSION: '1.18.1'


build_job:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    expire_in: 5 days
    paths:
      - WebCartographerColorExporter/bin/packages/*.zip
      - WebCartographer/bin/packages/*.zip
  before_script:
    - 'mkdir $VINTAGE_STORY_MODDING'
    - 'curl -o $VINTAGE_STORY_MODDING/server.tar.gz https://cdn.vintagestory.at/gamefiles/${SERVER_TYPE}/vs_server_${SERVER_VERSION}.tar.gz'
    - 'tar -xzf $VINTAGE_STORY_MODDING/server.tar.gz -C $VINTAGE_STORY_MODDING'
  script:
    - cd build
    - dotnet restore
    - dotnet run -v d --target="PackageMod"
    - dotnet run -v d--target="Package"
