name: Build VintageAtlas

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Cache Vintage Story libs
      uses: actions/cache@v4
      with:
        path: ~/vintagestory
        key: ${{ runner.os }}-vs-1.20.1
    
    - name: Download Vintage Story (if not cached)
      run: |
        if [ ! -d ~/vintagestory ]; then
          echo "Downloading Vintage Story 1.20.1..."
          mkdir -p ~/vintagestory
          wget -q https://cdn.vintagestory.at/gamefiles/stable/vs_archive_1.20.1.tar.gz
          tar -xzf vs_archive_1.20.1.tar.gz -C ~/vintagestory
          rm vs_archive_1.20.1.tar.gz
        else
          echo "Using cached Vintage Story"
        fi
    
    - name: Restore dependencies
      run: dotnet restore VintageAtlas/VintageAtlas.csproj
      env:
        VINTAGE_STORY: ${{ github.workspace }}/../vintagestory
    
    - name: Build
      run: dotnet build VintageAtlas/VintageAtlas.csproj --configuration Release --no-restore
      env:
        VINTAGE_STORY: ${{ github.workspace }}/../vintagestory
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VintageAtlas-build-${{ github.sha }}
        path: VintageAtlas/bin/Release/Mods/vintageatlas/
        retention-days: 7

